version: 2.1

orbs:
  tools: replikativ/clj-tools@0

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          setup_cljs: false
          context: dockerhub-deploy
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/integrationtest-cassandra:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/build:
          context: dockerhub-deploy
          jarname: "konserve-cassandra"
          requires:
            - tools/setup
      - tools/deploy-snapshot:
          jarname: "konserve-cassandra"
          context:
            - clojars-deploy
            - dockerhub-deploy
          filters:
            branches:
              only: development
          requires:
            - tools/setup
            - tools/format
            - tools/integrationtest-cassandra
            - tools/build
      - tools/deploy-release:
          jarname: "konserve-cassandra"
          context:
            - clojars-deploy
            - dockerhub-deploy
          filters:
            branches:
              only: master
          requires:
            - tools/setup
            - tools/format
            - tools/integrationtest-cassandra
            - tools/build
